import { expect, test } from '@playwright/test';

test('hosts can find, preview and save songs across languages without starting an external player early', async ({ page }, info) => {
  test.skip(!['mobile-320', 'mobile-390', 'desktop'].includes(info.project.name));
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.route('**/api/visitor-welcome', route => route.fulfill({ json: { enabled: false } }));
  const playerRequests: string[] = [];
  await page.route('https://www.youtube-nocookie.com/**', route => {
    playerRequests.push(route.request().url());
    return route.fulfill({ contentType: 'text/html', body: '<p>External song player fixture</p>' });
  });
  await page.goto('/customize?occasion=wedding&theme=modern');
  await page.getByRole('button', { name: 'Design', exact: true }).click();
  await page.getByRole('tab', { name: 'Music & layout', exact: true }).click();
  await page.getByLabel('A soundtrack for your story').check();
  await page.getByRole('button', { name: 'Song collection', exact: true }).click();
  const languages = page.getByRole('group', { name: 'Song language', exact: true });
  await languages.getByRole('button', { name: 'Punjabi', exact: true }).click();
  await page.getByRole('searchbox', { name: 'Search songs', exact: true }).fill('Diljit');
  await page.getByRole('combobox', { name: 'Song mood', exact: true }).selectOption('Romantic');
  const choices = page.getByRole('list', { name: 'Song collection', exact: true });
  await expect(choices.getByRole('button', { name: /^Choose / })).toHaveCount(1);
  await page.getByRole('button', { name: 'Choose Lover', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Choose Lover', exact: true })).toHaveAttribute('aria-pressed', 'true');
  expect(playerRequests).toEqual([]);
  await expect(page.locator('.song-dialog iframe')).toHaveCount(0);
  await page.getByRole('button', { name: 'Preview Lover', exact: true }).click();
  await expect(page.locator('.song-dialog iframe')).toHaveAttribute('src', /\/mH_LFkWxpI0\?.*autoplay=0/);
  await expect.poll(() => playerRequests.length).toBe(1);
  await page.getByRole('button', { name: 'Close song player', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Preview Lover', exact: true })).toBeFocused();
  await page.getByRole('searchbox', { name: 'Search songs', exact: true }).fill('');
  await languages.getByRole('button', { name: 'English', exact: true }).click();
  await expect(choices.getByRole('button', { name: /^Choose / })).toHaveCount(2);
  await page.getByRole('button', { name: 'Choose Perfect', exact: true }).click();
  await page.getByRole('button', { name: 'Save draft', exact: true }).click();
  await expect(page.locator('.editor-workspace-status')).toHaveAttribute('data-save-state', 'saved');
  await page.reload();
  await page.getByRole('button', { name: 'Design', exact: true }).click();
  await page.getByRole('tab', { name: 'Music & layout', exact: true }).click();
  await expect(languages.getByRole('button', { name: 'English', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(page.getByRole('button', { name: 'Choose Perfect', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(page.locator('.song-dialog iframe')).toHaveCount(0);
  expect(playerRequests).toHaveLength(1);
  await page.getByRole('button', { name: 'Our song', exact: true }).click();
  await expect(page.locator('.song-dialog iframe')).toHaveAttribute('src', /\/2Vv-BfVoq4g\?.*autoplay=0/);
  await page.getByRole('button', { name: 'Close song player', exact: true }).click();
  expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(0);
  expect(errors, 'No browser runtime errors').toEqual([]);
});
