import { readFile, mkdir } from "node:fs/promises";
import { randomBytes } from "node:crypto";
import { createClient } from "@supabase/supabase-js";
import { expect, test } from "@playwright/test";
import { demoInvitation } from "../src/data/demo-invitation";

test.use({ trace: "off", screenshot: "off", video: "off" });

test("wedding collection plays the supplied recording on demand and saves a Bollywood choice", async ({ page }, info) => {
  test.skip(info.project.name !== "mobile-360");
  const audioRequests: string[] = [];
  page.on("request", request => { if (request.url().includes("/audio/") && request.url().endsWith(".mp3")) audioRequests.push(request.url()); });
  await page.goto("/customize?occasion=wedding&theme=modern");
  await page.getByRole("button", { name: "Design", exact: true }).click();
  await page.getByLabel("A soundtrack for your story").check();
  await expect(page.getByRole("button", { name: /Dulhe Ki Behen Brigade/ })).toHaveAttribute("aria-pressed", "true");
  expect(audioRequests).toHaveLength(0);
  await page.getByRole("button", { name: "Play music", exact: true }).click();
  await expect(page.getByRole("button", { name: "Pause music", exact: true })).toBeVisible();
  await expect.poll(() => page.locator(".editor-music audio").evaluate((audio: HTMLAudioElement) => audio.currentTime)).toBeGreaterThan(0);
  await page.getByRole("button", { name: /London Thumakda/ }).click();
  await expect(page.locator(".editor-music audio")).toHaveCount(0);
  await page.route("https://www.youtube-nocookie.com/**", route => route.fulfill({ contentType: "text/html", body: "<p>External player fixture</p>" }));
  await page.getByRole("button", { name: "Our song", exact: true }).click();
  await expect(page.locator(".song-dialog iframe")).toHaveAttribute("src", /udra3Mfw2oo.*autoplay=0/);
  await page.getByRole("button", { name: "Close song player" }).click();
  await page.getByRole("button", { name: "Save draft", exact: true }).click();
  await page.reload();
  await page.getByRole("button", { name: "Design", exact: true }).click();
  await expect(page.getByRole("button", { name: /London Thumakda/ })).toHaveAttribute("aria-pressed", "true");
  for (const width of [320, 360, 768, 1440]) { await page.setViewportSize({ width, height: 900 }); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); }
  await page.setViewportSize({ width: 360, height: 800 });
  await page.getByRole("button", { name: "Upload your audio", exact: true }).click();
  await expect(page.getByRole("link", { name: "Sign in to add audio" })).toBeVisible();
});

test("custom MP3 uploads, persists, stays private, replaces and removes from the invitation", async ({ page, browser }, info) => {
  test.skip(process.env.INVITLY_INTEGRATION !== "1" || info.project.name !== "mobile-360", "Disposable local Supabase only.");
  test.setTimeout(180000);
  const settings = JSON.parse(await readFile("artifacts/local-supabase.json", "utf8"));
  if (!["127.0.0.1", "localhost"].includes(new URL(settings.API_URL).hostname)) throw new Error("Local tests only.");
  const admin = createClient(settings.API_URL, settings.SECRET_KEY || settings.SERVICE_ROLE_KEY, { auth: { persistSession: false, autoRefreshToken: false } });
  const password = randomBytes(24).toString("base64url");
  const email = `audio-${randomBytes(8).toString("hex")}@example.test`;
  const account = await admin.auth.admin.createUser({ email, password, email_confirm: true });
  expect(account.error).toBeNull();
  const userId = account.data.user!.id;
  const slug = `audio-${randomBytes(8).toString("hex")}`;
  let eventId = "";
  const guest = await browser.newContext({ baseURL: info.project.use.baseURL });
  try {
    const created = await admin.from("events").insert({ owner_id: userId, slug, title: "Local audio preview", theme_id: "modern", invitation_content: { ...demoInvitation, slug }, music_enabled: true }).select("id").single();
    expect(created.error).toBeNull(); eventId = created.data!.id;
    await page.goto("/login");
    await page.getByLabel("Email address", { exact: true }).fill(email);
    await page.locator("#password").fill(password);
    await page.getByRole("button", { name: "Sign in", exact: true }).click();
    await expect(page).toHaveURL(/\/dashboard$/);
    await page.goto(`/customize?event=${eventId}`);
    await page.getByRole("button", { name: "Design", exact: true }).click();
    await page.getByRole("button", { name: "Upload your audio", exact: true }).click();
    await page.getByLabel("Your MP3 file").setInputFiles({ name: "fake.mp3", mimeType: "audio/mpeg", buffer: Buffer.from("This is not an MP3 file") });
    await page.getByRole("button", { name: "Upload audio", exact: true }).click();
    await expect(page.locator(".editor-custom-audio [role=status]")).toContainText("readable MP3", { timeout: 20000 });
    await page.getByLabel("Your MP3 file").setInputFiles("public/audio/dulhe-ki-behen-brigade.mp3");
    await page.getByRole("button", { name: "Upload audio", exact: true }).click();
    await expect(page.locator(".editor-custom-audio [role=status]")).toContainText("Audio uploaded", { timeout: 30000 });
    await page.getByRole("button", { name: "Play music", exact: true }).click();
    await expect(page.getByRole("button", { name: "Pause music", exact: true })).toBeVisible({ timeout: 15000 });
    const firstUrl = await page.locator(".editor-music audio").getAttribute("src");
    expect((await guest.request.get(firstUrl!)).status()).toBe(404);
    const accounts = JSON.parse(await readFile("artifacts/integration/accounts.json", "utf8"));
    const otherHost = await guest.newPage();
    await otherHost.goto("/login");
    await otherHost.getByLabel("Email address", { exact: true }).fill(accounts.B.email);
    await otherHost.locator("#password").fill(accounts.B.password);
    await otherHost.getByRole("button", { name: "Sign in", exact: true }).click();
    await expect(otherHost).toHaveURL(/\/dashboard$/);
    expect((await guest.request.get(firstUrl!)).status()).toBe(404);
    const ownerClient = createClient(settings.API_URL, settings.PUBLISHABLE_KEY, { auth: { persistSession: false, autoRefreshToken: false } });
    expect((await ownerClient.auth.signInWithPassword({ email, password })).error).toBeNull();
    const audioId = firstUrl!.split("/").pop();
    expect((await ownerClient.storage.from("event-audio").download(`${eventId}/${audioId}.mp3`)).error).not.toBeNull();
    await ownerClient.auth.signOut({ scope: "local" });
    await page.getByRole("button", { name: "Pause music", exact: true }).click();
    await page.getByRole("button", { name: "Save draft", exact: true }).click();
    await expect(page.locator(".editor-feedback .form-success")).toBeVisible({ timeout: 20000 });
    await page.reload();
    await page.getByRole("button", { name: "Design", exact: true }).click();
    await expect(page.locator(".editor-uploaded-audio")).toContainText("dulhe-ki-behen-brigade.mp3");
    await page.getByRole("button", { name: "Share", exact: true }).click();
    await page.getByRole("button", { name: "Publish invitation", exact: true }).click();
    await expect.poll(async () => (await admin.from("events").select("is_published").eq("id", eventId).single()).data?.is_published).toBe(true);
    const publicAudio = await guest.request.get(firstUrl!, { headers: { Range: "bytes=0-9" } });
    expect(publicAudio.status()).toBe(206);
    expect(publicAudio.headers()["content-type"]).toBe("audio/mpeg");
    expect(publicAudio.headers()["cache-control"]).toBe("private, no-store");
    expect(await publicAudio.body()).toEqual((await readFile("public/audio/dulhe-ki-behen-brigade.mp3")).subarray(0, 10));
    await admin.from("events").update({ is_published: false }).eq("id", eventId);
    expect((await guest.request.get(firstUrl!)).status()).toBe(404);
    await admin.from("events").update({ is_published: true }).eq("id", eventId);
    await page.getByRole("button", { name: "Design", exact: true }).click();
    await page.getByLabel("Your MP3 file").setInputFiles({ name: "Our welcome.mp3", mimeType: "audio/mpeg", buffer: await readFile("public/audio/dulhe-ki-behen-brigade.mp3") });
    await page.getByRole("button", { name: "Replace audio", exact: true }).click();
    await expect(page.locator(".editor-uploaded-audio")).toContainText("Our welcome.mp3", { timeout: 30000 });
    await page.getByRole("button", { name: "Save draft", exact: true }).click();
    await expect(page.locator(".editor-feedback .form-success")).toBeVisible({ timeout: 20000 });
    expect((await guest.request.get(firstUrl!)).status()).toBe(404);
    await page.getByRole("button", { name: "Play music", exact: true }).click();
    await expect(page.getByRole("button", { name: "Pause music", exact: true })).toBeVisible();
    const secondUrl = await page.locator(".editor-music audio").getAttribute("src");
    expect((await guest.request.get(secondUrl!, { headers: { Range: "bytes=0-1" } })).status()).toBe(206);
    await page.getByRole("button", { name: "Pause music", exact: true }).click();
    await mkdir("artifacts/screenshots", { recursive: true });
    await page.locator(".editor-custom-audio").screenshot({ path: "artifacts/screenshots/custom-audio-mobile.png" });
    await page.getByRole("button", { name: "Remove custom audio", exact: true }).click();
    await page.getByRole("button", { name: "Save draft", exact: true }).click();
    await expect(page.locator(".editor-feedback .form-success")).toBeVisible({ timeout: 20000 });
    expect((await guest.request.get(secondUrl!)).status()).toBe(404);
    await page.reload();
    await page.getByRole("button", { name: "Design", exact: true }).click();
    await page.getByRole("button", { name: "Upload your audio", exact: true }).click();
    await expect(page.locator(".editor-uploaded-audio")).toHaveCount(0);
  } finally {
    if (eventId) { const { data } = await admin.storage.from("event-audio").list(eventId); if (data?.length) await admin.storage.from("event-audio").remove(data.map(file => `${eventId}/${file.name}`)); }
    await guest.close();
    expect((await admin.auth.admin.deleteUser(userId)).error).toBeNull();
  }
});
