import { LegalPage } from "@/components/legal/legal-page";
import { legalDetails } from "@/lib/legal";
import { publicMetadata } from "@/lib/seo";
export const metadata = { ...publicMetadata("Privacy policy", "How Invitly handles account, invitation and guest information.", "/privacy"), robots: { index: legalDetails.complete, follow: true } };
export default function PrivacyPage() {
  return <LegalPage title="Privacy policy">
    <section><h2>What you share with Invitly</h2><p>Hosts provide account details, invitation text, dates, locations, photographs, audio and guest details. Guests may submit an RSVP, party size and a note through a personal invitation link. Please share only information you have permission to use, and avoid including sensitive information in RSVP notes.</p></section>
    <section><h2>How the information is used</h2><p>Invitly uses these details to authenticate hosts, save and display invitations, deliver account emails, manage guest access and show responses to the invitation’s host. Hosting and authentication services may process connection and security logs to operate the service and prevent abuse.</p></section>
    <section><h2>Who can see an invitation</h2><p>A published shared link can be opened and forwarded by anyone who has it. Personal guest links provide access to the schedule and RSVP options selected for that guest. Treat these links as private: someone who receives a forwarded personal link may be able to use it. Hosts can replace guest links and make their invitation private.</p><p>Hosts can see their guest list and responses and can export this information. Contact your host to correct or remove information they supplied about you. Search indexing is disabled for invitation and host pages, but this does not prevent a recipient from sharing or saving content.</p></section>
    <section><h2>Cookies and information on your device</h2><p>Invitly uses essential authentication cookies to keep hosts signed in. The editor can store an invitation draft in your browser to help preserve your work. Browser preferences may remember choices such as music volume. Clearing browser storage removes these local copies; it does not remove information saved to a host account.</p><p>The app does not currently include advertising or analytics trackers. No optional tracking cookies are enabled by this app. If optional tracking is introduced, this notice and the relevant consent controls must be updated before it runs.</p></section>
    <section><h2>External services</h2><p>Account and invitation storage use Supabase. Videos, maps, calendar services and messaging links may connect to external providers when you choose to open them. Embedded videos and maps are loaded only after you choose to load them. Those providers receive connection information and handle data under their own privacy notices.</p></section>
    <section><h2>Storage and your choices</h2><p>Hosts can edit invitation details, remove uploaded photos, remove guests and their RSVP records, or unpublish an invitation using the available controls. Unpublishing restricts guest access; it does not delete the host’s saved data. Copies already exported or saved by recipients are outside these controls.</p><p>Depending on your location, you may have rights to request access, correction, deletion or restriction of your personal information. The operator’s contact details will appear below. Applicable retention periods, infrastructure locations and any additional service-provider arrangements must be confirmed for the live deployment.</p></section>
  </LegalPage>;
}
