import { LegalPage } from "@/components/legal/legal-page";
import { legalDetails } from "@/lib/legal";
import { publicMetadata } from "@/lib/seo";
export const metadata = { ...publicMetadata("Privacy policy", "How Invitly handles account, invitation and guest information.", "/privacy"), robots: { index: legalDetails.complete, follow: true } };
export default function PrivacyPage() {
  return <LegalPage title="Privacy policy">
    <section><h2>What you share with Invitly</h2><p>Hosts provide account details, invitation text, dates, locations, photographs, audio and guest details. Guests may submit an RSVP, party size and a note through a personal invitation link. Please share only information you have permission to use, and avoid including sensitive information in RSVP notes.</p></section>
    <section><h2>How the information is used</h2><p>Invitly uses these details to authenticate hosts, save and display invitations, deliver account emails, manage guest access and show responses to the invitation’s host. Hosting and authentication services may process connection and security logs to operate the service and prevent abuse.</p></section>
    <section><h2>Introducing yourself</h2><p>When the welcome form is enabled, we ask for your name and reason for visiting before you continue browsing the collection. Selecting Continue sends those answers, the public page you are visiting, the referring website when available and the submission time to the Invitly team through its configured webhook provider. We use this information to understand visitors’ interests. The form does not send passwords, account tokens, private invitation links or your IP address to that provider.</p><p>After a successful submission, your browser remembers a completion timestamp for 30 days so the form does not ask again. Your name and answer are not saved in this browser preference. Clearing browser storage removes the preference. Welcome submissions are separate from account registration and are not a count of everyone who visits the website. The operator must confirm the receiving provider and its retention period before launch.</p></section>
    <section><h2>Who can see an invitation</h2><p>A published shared link can be opened and forwarded by anyone who has it. Personal guest links provide access to the schedule and RSVP options selected for that guest. Treat these links as private: someone who receives a forwarded personal link may be able to use it. Hosts can replace guest links and make their invitation private.</p><p>Hosts can see their guest list and responses and can export this information. Contact your host to correct or remove information they supplied about you. Search indexing is disabled for invitation and host pages, but this does not prevent a recipient from sharing or saving content.</p></section>
    <section><h2>Cookies and information on your device</h2><p>Invitly uses essential authentication cookies to keep hosts signed in. The editor can store an invitation draft in your browser to help preserve your work. Browser preferences may remember choices such as music volume. Clearing browser storage removes these local copies; it does not remove information saved to a host account.</p></section>
    <section><h2>Advertising</h2><p>Our homepage loads Google AdSense to support advertising. Google receives connection information, such as your IP address and browser information, when its code loads. Google and its advertising partners may use cookies or similar technologies to deliver and measure ads, prevent fraud, and personalize advertising according to applicable settings and consent choices.</p><p>Learn <a href="https://policies.google.com/technologies/partner-sites" target="_blank" rel="noopener noreferrer">how Google uses information from partner sites</a> and manage personalization in <a href="https://myadcenter.google.com/" target="_blank" rel="noopener noreferrer">Google My Ad Center</a>. You can also control cookies through your browser settings.</p></section>
    <section><h2>External services</h2><p>Account and invitation storage use Supabase. Videos, maps, calendar services and messaging links may connect to external providers when you choose to open them. Embedded videos and maps are loaded only after you choose to load them. Those providers receive connection information and handle data under their own privacy notices.</p></section>
    <section><h2>Storage and your choices</h2><p>Hosts can edit invitation details, remove uploaded photos, remove guests and their RSVP records, or unpublish an invitation using the available controls. Unpublishing restricts guest access; it does not delete the host’s saved data. Copies already exported or saved by recipients are outside these controls.</p><p>Depending on your location, you may have rights to request access, correction, deletion or restriction of your personal information. The operator’s contact details will appear below. Applicable retention periods, infrastructure locations and any additional service-provider arrangements must be confirmed for the live deployment.</p></section>
  </LegalPage>;
}
