import type { Metadata } from "next";
import Link from "next/link";
import { Flower } from "@/components/brand";
import { blogTopics, getBlogTopic, blogReadingMinutes } from "@/data/blog";
import { getPublishedPosts } from "@/lib/blog";

export const metadata: Metadata = { title: "The Invitly journal", description: "Thoughtful invitation wording, practical hosting details and ideas for Indian celebrations. Find a little inspiration for your next gathering.", alternates: { canonical: "/blog" } };

export default async function BlogPage() {
  const posts = await getPublishedPosts();
  return <><section className="journal-intro container"><span className="eyebrow"><Flower /> NOTES FROM INVITLY</span><h1>Good words for<br /><em>lovely moments.</em></h1><p>A little inspiration for the invitation. A few thoughtful details for the day. Make every welcome feel like you.</p></section><nav className="journal-topics container" aria-label="Blog topics">{blogTopics.map(topic => <Link key={topic.slug} href={`/blog/category/${topic.slug}`}>{topic.name}<span aria-hidden="true">↗</span></Link>)}</nav><section className="journal-library container" aria-labelledby="journal-library-title"><div className="journal-section-heading"><span className="eyebrow">WORDS, WELCOME & TOGETHERNESS</span><h2 id="journal-library-title">From the journal</h2></div><div className="journal-grid">{posts.map((post, index) => <article className={`journal-card journal-topic-${post.topic}`} key={post.slug}><Link className="journal-card-art" href={`/blog/${post.slug}`} aria-label={`Read ${post.title}`}><span className="journal-card-edition">INVITLY NOTES · {String(index + 1).padStart(2, "0")}</span><Flower /><span>{getBlogTopic(post.topic)!.name}</span></Link><div className="journal-card-copy"><p className="journal-card-meta">{getBlogTopic(post.topic)!.name} <span aria-hidden="true">·</span> {blogReadingMinutes(post)} min read</p><h3><Link href={`/blog/${post.slug}`}>{post.title}</Link></h3><p>{post.excerpt}</p><Link className="journal-read-link" href={`/blog/${post.slug}`}>Read the story <span aria-hidden="true">↗</span></Link></div></article>)}</div></section><section className="journal-invitation-cta container"><Flower /><h2>Found the words?<br /><em>Find your invitation.</em></h2><p>Choose a design, add your details, and make every line your own.</p><Link href="/templates" className="button">Explore the collection <span aria-hidden="true">↗</span></Link></section></>;
}
